# Site configuration
title: "Privacy Project Fantasy Football Weekly Report"
tagline: "Your weekly dose of fantasy football analysis and insights"
description: "Comprehensive weekly fantasy football analysis, power rankings, and entertaining commentary from each week of the season."
logo: "🏈"
author: "The Commissioner"

# Site settings
url: "https://chasecmathis.github.io"
baseurl: "/ff-newsletter"

# Theme
remote_theme: daviddarnes/alembic@main

# Navigation
navigation_header:
- title: Home
  url: /
- title: Archive
  url: /#archive

# Colors (football theme)
accent_color: '#2e7d32'

# Plugins (GitHub Pages supported plugins)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-remote-theme

# Site settings
encoding: utf-8
lang: en-GB
timezone: America/Chicago

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  newsletters:
    output: true
    permalink: /newsletters/:name/

# Markdown settings
markdown: CommonMark
highlighter: rouge
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# Sass
sass:
  style: compressed