# Site configuration
title: "Privacy Project Fantasy Football Weekly Report"
tagline: "Your weekly dose of fantasy football analysis and insights"
description: "Weekly fantasy football analysis, power rankings, and strategic insights for competitive league play."
author: "The Commissioner"
logo: "⚡"

# Site settings
url: "https://chasecmathis.github.io"
baseurl: "/ff-newsletter"

# Theme
remote_theme: daviddarnes/alembic@main

# Navigation
navigation_header:
- title: Home
  url: /
- title: Archive
  url: /#newsletter-archive

# Professional color scheme
accent_color: '#2e7d32'

# Plugins (GitHub Pages supported plugins)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

# Site settings
encoding: utf-8
lang: en-GB